package mybatis.pojo;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_person.person_id
     *
     * @mbg.generated
     */
    private String personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_person.lib_id
     *
     * @mbg.generated
     */
    private String libId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_person.birthday
     *
     * @mbg.generated
     */
    private Long birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_person.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_person.card_type
     *
     * @mbg.generated
     */
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_person.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_person.census_register
     *
     * @mbg.generated
     */
    private String censusRegister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_person.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_person.nation
     *
     * @mbg.generated
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_person.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_person.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_person.person_id
     *
     * @return the value of ps_person.person_id
     *
     * @mbg.generated
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_person.person_id
     *
     * @param personId the value for ps_person.person_id
     *
     * @mbg.generated
     */
    public void setPersonId(String personId) {
        this.personId = personId == null ? null : personId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_person.lib_id
     *
     * @return the value of ps_person.lib_id
     *
     * @mbg.generated
     */
    public String getLibId() {
        return libId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_person.lib_id
     *
     * @param libId the value for ps_person.lib_id
     *
     * @mbg.generated
     */
    public void setLibId(String libId) {
        this.libId = libId == null ? null : libId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_person.birthday
     *
     * @return the value of ps_person.birthday
     *
     * @mbg.generated
     */
    public Long getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_person.birthday
     *
     * @param birthday the value for ps_person.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_person.gender
     *
     * @return the value of ps_person.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_person.gender
     *
     * @param gender the value for ps_person.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_person.card_type
     *
     * @return the value of ps_person.card_type
     *
     * @mbg.generated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_person.card_type
     *
     * @param cardType the value for ps_person.card_type
     *
     * @mbg.generated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_person.id_card
     *
     * @return the value of ps_person.id_card
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_person.id_card
     *
     * @param idCard the value for ps_person.id_card
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_person.census_register
     *
     * @return the value of ps_person.census_register
     *
     * @mbg.generated
     */
    public String getCensusRegister() {
        return censusRegister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_person.census_register
     *
     * @param censusRegister the value for ps_person.census_register
     *
     * @mbg.generated
     */
    public void setCensusRegister(String censusRegister) {
        this.censusRegister = censusRegister == null ? null : censusRegister.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_person.name
     *
     * @return the value of ps_person.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_person.name
     *
     * @param name the value for ps_person.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_person.nation
     *
     * @return the value of ps_person.nation
     *
     * @mbg.generated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_person.nation
     *
     * @param nation the value for ps_person.nation
     *
     * @mbg.generated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_person.remark
     *
     * @return the value of ps_person.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_person.remark
     *
     * @param remark the value for ps_person.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_person.create_time
     *
     * @return the value of ps_person.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_person.create_time
     *
     * @param createTime the value for ps_person.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}