package mybatis.mapper;

import java.util.List;
import mybatis.pojo.Person;
import mybatis.pojo.PersonExample;
import org.apache.ibatis.annotations.Param;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_person
     *
     * @mbg.generated
     */
    long countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_person
     *
     * @mbg.generated
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_person
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String personId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_person
     *
     * @mbg.generated
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_person
     *
     * @mbg.generated
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_person
     *
     * @mbg.generated
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_person
     *
     * @mbg.generated
     */
    Person selectByPrimaryKey(String personId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_person
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_person
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_person
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_person
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Person record);
}